# Generated by Django 4.0.4 on 2022-05-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yazgecapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthOfDate',
        ),
    ]
