# Generated by Django 4.0.4 on 2022-05-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazgecapp', '0002_remove_user_birthofdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='context',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
