# Generated by Django 4.0.4 on 2022-05-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazgecapp', '0003_post_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ownerId',
            field=models.BigIntegerField(),
        ),
    ]
