# Generated by Django 4.0.4 on 2022-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazgecapp', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ownerUsername',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
