# Generated by Django 4.0.4 on 2022-05-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazgecapp', '0007_remove_post_ownerid_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user2',
            field=models.CharField(max_length=100),
        ),
    ]
