# Generated by Django 4.0.4 on 2022-05-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazgecapp', '0008_alter_friendship_user1_alter_friendship_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=2000),
        ),
    ]
